export const initialFilesystem = {
    "/": {},
    "/Users/": {},
    "/Users/Admin/": {},
    "/Users/Admin/Desktop/": {},
    "/Users/Admin/Desktop/Browser.desktop": {},
    "/Users/Admin/Desktop/File Explorer.desktop": {},
    "/Users/Admin/Desktop/Recycle Bin.desktop": {},
    "/Users/Admin/Desktop/Settings.desktop": {},
    "/Users/Admin/Desktop/Games.desktop": {},
    "/Users/Admin/Desktop/Clock.desktop": {},
    "/Users/Admin/Desktop/Calculator.desktop": {},
    "/Users/Admin/Desktop/Arcane Legacy.desktop": {},
    "/Users/Admin/Desktop/TowerForge Defense.desktop": {},
    "/Users/Admin/Documents/": {},
    "/Users/Admin/Documents/Work/": {},
    "/Users/Admin/Documents/Work/Project_Proposal.pdf": {},
    "/Users/Admin/Documents/Work/Meeting_Notes.txt": {},
    "/Users/Admin/Documents/Personal/": {},
    "/Users/Admin/Documents/Personal/resume_2025.pdf": {},
    "/Users/Admin/Documents/Personal/travel_itinerary.xlsx": {},
    "/Users/Admin/Documents/Personal/recipes.txt": {},
    "/Users/Admin/Pictures/": {},
    "/Users/Admin/Pictures/Wallpapers/": {},
    "/Users/Admin/Pictures/Wallpapers/default_wallpaper.jpg": {
        "url": "https://images.unsplash.com/photo-1747985323857-5c1c16b2ac47?q=80&w=1450&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    "/Users/Admin/Pictures/Wallpapers/snowy_mountain.jpg": {
        "url": "https://images.unsplash.com/photo-1573671935871-77305106a2f2?q=80&w=1464&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    "/Users/Admin/Pictures/Wallpapers/galaxy.jpg": {
        "url": "https://images.unsplash.com/photo-1741282198587-65bf77e6075d?q=80&w=1091&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    "/Users/Admin/Pictures/Wallpapers/hills.jpg": {
        "url": "https://images.unsplash.com/photo-1746937807433-05748b80caf4?q=80&w=1674&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    "/Users/Admin/Pictures/Wallpapers/dolomites.jpg": {
        "url": "https://images.unsplash.com/photo-1745669754254-c30c98e5f8b1?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    "/Users/Admin/Pictures/Wallpapers/sunset.jpg": {},
    "/Users/Admin/Pictures/Wallpapers/abstract.png": {},
    "/Users/Admin/Pictures/Family/": {},
    "/Users/Admin/Pictures/Family/2024_birthday_party_01.jpg": {},
    "/Users/Admin/Pictures/Family/2024_holiday_gathering.png": {},
    "/Users/Admin/Pictures/Screenshots/": {},
    "/Users/Admin/Pictures/Screenshots/screenshot_2025-07-15.png": {},
    "/Users/Admin/Downloads/": {},
    "/Users/Admin/Downloads/project_presentation.pptx": {},
    "/Users/Admin/Downloads/software_update_installer.exe": {},
    "/Users/Admin/Downloads/ebook_collection.zip": {},
    "/Users/Admin/Music/": {},
    "/Users/Admin/Music/Favorite_Artists/": {},
    "/Users/Admin/Music/Favorite_Artists/Artist_A/album1_song1.mp3": {},
    "/Users/Admin/Music/Favorite_Artists/Artist_B/album2_song3.flac": {},
    "/Users/Admin/Music/workout_playlist.m3u": {},
    "/Users/Admin/Music/chill_mix.pls": {},
    "/Users/Admin/Videos/": {},
    "/Users/Admin/Videos/Vacation_2024/": {},
    "/Users/Admin/Videos/Vacation_2024/day_1_highlights.mp4": {},
    "/Users/Admin/Videos/Vacation_2024/scenic_views.mov": {},
    "/Users/Admin/Videos/Funny_Clips/cat_video.avi": {},
    "/Users/Admin/settings.ini": {
        "contents": "desktop_background=/Users/Admin/Pictures/Wallpapers/galaxy.jpg"
    },
    "/Games/": {},
    "/System/": {},
    "/System/SystemInfo.txt": {},
    "/System/config/": {},
    "/System/config/system.conf": {},
    "/System/config/network.conf": {},
    "/System/drivers/": {},
    "/System/drivers/network.sys": {},
    "/System/drivers/audio.sys": {},
    "/System/drivers/video.sys": {},
    "/System/drivers/input.sys": {},
    "/System/fonts/": {},
    "/System/fonts/arial.ttf": {},
    "/System/fonts/times_new_roman.ttf": {},
    "/System/boot.ini": {},
    "/System/kernel.sys": {},
    "/System/log/": {},
    "/System/log/system_events.log": {},
    "/System/log/error_log.txt": {},
    "/Applications/": {},
    "/Applications/Browser.app": {},
    "/Applications/FileExplorer.app": {},
    "/Applications/Settings.app": {},
    "/Applications/TextEditor.app": {},
    "/Applications/MusicPlayer.app": {},
    "/Applications/ImageViewer.app": {},
    "/Applications/Feedback.app": {},
    "/Applications/Calculator.app": {},
    "/Applications/Terminal.app": {},
    "/Applications/EmailClient.app": {},
    "/Applications/Calendar.app": {},
    "/Applications/Maps.app": {},
    "/Applications/Weather.app": {},
    "/Applications/Photos.app": {},
    "/Applications/VideoPlayer.app": {},
    "/Applications/Spreadsheet.app": {},
    "/Applications/Presentation.app": {},
    "/Applications/WordProcessor.app": {},
    "/Applications/CodeEditor.app": {},
    "/Applications/GameCenter.app": {},
    "/Applications/Notes.app": {},
    "/Applications/Contacts.app": {},
    "/Applications/Clock.app": {},
    "/Applications/Antivirus.app": {},
    "/Applications/PDF_Reader.app": {},
    "/Applications/CloudStorage.app": {},
    "/Applications/VPN.app": {},
    "/Applications/ArcaneLegacy.app": {},
    "/Applications/TowerForgeDefense.app": {},
    "/Applications/SpaceAdventures.app": {},
    "/.trash/": {},
    "/.trash/1721052000000-Q3_Financial_Report.docx": {
        "originalPath": "/Users/Admin/Documents/Work/Q3_Financial_Report.docx",
        "deletedAt": "2025-07-15T14:00:00.000Z",
        "data": { "contents": "This was the Q3 financial report. It has been deleted." }
    }
};
